### ISSUE TITLE
official data split?

### ISSUE THREAD

**Issue by 7LFB** [guanqj932/Category-wise-Residual-Attention-Learning#1]
Recently I read your another great work, 'Diagnose like a Radiologist: Attention Guided CNN for Thorax Disease Classification', and I was inspired a lot. I want to confirm that if the results is evaluated on the official data split?

**Comment by guanqj932** [comment]
@7LFB  Thanks for your attention. This paper is evaluated on the offical data split while "Diagnose like a Radiologist" is not.
